### ISSUE TITLE
WG0 step use same singularity image as wg1?

### ISSUE THREAD

**Issue by Marwansha** [sc-eQTLgen-consortium/WG0-pipeline-preprocessing#1]
hello,  i have couple of question considering this step 

1)to implement the wg0 i want to ask if it use  same singularity image as wg1? 

2), inside  thepreprocessong.yaml file , the fastq folde path    ,for my case i have 2 folders for each flow cells each containg the fastq  ,  shall i provide the 2 paths?

thanks for your time and help

**Comment by mvochteloo** [comment]
Hi,

First and foremost, the code contained in this repository is in development and not yet ready for public use. A detailed manual will be provided once the pipeline is ready for release.

Regarding your questions, 1) for WG0 there will be a dedicated singularity image which is not yet available at this time. 
2) A single fastq folder as input is accepted at this point. If your directory contains distinct pools you can choose to run the pipeline on each folder separately or combine the fastqs into a single input folder.
